### ISSUE TITLE
Client-side crash when breaking blocks

### ISSUE THREAD

**Issue by unilock** [AlphaMode/Tamago#1]
With Tamago installed, attempting to break any block in survival mode crashes the client.

<details>
<summary>"crash-2023-11-13_15.48.43-client.txt"</summary>

```
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 2023-11-13 15:48:43
Description: Unexpected error

java.lang.InstantiationError: me.alphamode.tamago.Tamago$BreakSpeed
	at net.minecraft.class_4970.handler$bfd000$porting_lib_entity$getDestroySpeed(io/github/fabricators_of_create/porting_lib/entity/mixin/common/BlockBehaviourMixin.java [porting_lib_entity.mixins.json]:21)
	at net.minecraft.class_4970.method_9594(class_4970.java:389)
	at net.minecraft.class_4970$class_4971.method_26165(class_4970.java:997)
	at net.minecraft.class_636.method_41930(class_636.java:180)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2910(class_636.java:175)
	at net.minecraft.class_310.method_1536(class_310.java:1736)
	at net.minecraft.class_310.method_1508(class_310.java:2049)
	at net.minecraft.class_310.method_1574(class_310.java:1883)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:125)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_4970.handler$bfd000$porting_lib_entity$getDestroySpeed(io/github/fabricators_of_create/porting_lib/entity/mixin/common/BlockBehaviourMixin.java [porting_lib_entity.mixins.json]:21)
	at net.minecraft.class_4970.method_9594(class_4970.java:389)
	at net.minecraft.class_4970$class_4971.method_26165(class_4970.java:997)
	at net.minecraft.class_636.method_41930(class_636.java:180)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2910(class_636.java:175)
	at net.minecraft.class_310.method_1536(class_310.java:1736)
	at net.minecraft.class_310.method_1508(class_310.java:2049)
Mixins in Stacktrace:
	net.minecraft.class_4970:
		io.github.fabricators_of_create.porting_lib.entity.mixin.common.BlockBehaviourMixin (porting_lib_entity.mixins.json)
		net.fabricmc.fabric.mixin.object.builder.AbstractBlockAccessor (fabric-object-builder-v1.mixins.json)
	net.minecraft.class_4970$class_4971:
		io.github.fabricators_of_create.porting_lib.mixin.common.BlockBehaviour$BlockStateBaseMixin (porting_lib_base.mixins.json)
	net.minecraft.class_636:
		dev.architectury.mixin.fabric.client.MixinMultiPlayerGameMode (architectury.mixins.json)
		net.fabricmc.fabric.mixin.event.interaction.client.ClientPlayerInteractionManagerMixin (fabric-events-interaction-v0.client.mixins.json)
		io.github.fabricators_of_create.porting_lib.mixin.client.MultiPlayerGameModeMixin (porting_lib_base.mixins.json)
		net.fabricmc.fabric.mixin.item.client.ClientPlayerInteractionManagerMixin (fabric-item-api-v1.client.mixins.json)
		com.jamieswhiteshirt.reachentityattributes.mixin.client.ClientPlayerInteractionManagerMixin (mixins.reach-entity-attributes.json)
		io.github.fabricators_of_create.porting_lib.entity.mixin.client.MultiPlayerGameModeMixin (porting_lib_entity.mixins.json)
	net.minecraft.class_310:
		io.github.fabricators_of_create.porting_lib.mixin.client.MinecraftMixin (porting_lib_base.mixins.json)
		net.fabricmc.fabric.mixin.networking.client.accessor.MinecraftClientAccessor (fabric-networking-api-v1.client.mixins.json)
		io.github.fabricators_of_create.porting_lib.data.mixin.MinecraftMixin (porting_lib_data.mixins.json)
		io.github.fabricators_of_create.porting_lib.entity.mixin.client.MinecraftMixin (porting_lib_entity.mixins.json)
		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (fabric-events-interaction-v0.client.mixins.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (fabric-registry-sync-v0.client.mixins.json)
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.client.mixins.json)
		io.github.fabricators_of_create.porting_lib.common.mixin.client.accessor.MinecraftAccessor (porting_lib_common.mixins.json)
		io.github.fabricators_of_create.porting_lib.config.mixin.client.MinecraftMixin (porting_lib_config.mixins.json)
		dev.architectury.mixin.fabric.client.MixinMinecraft (architectury.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.client.mixins.json)

-- Affected level --
Details:
	All players: 1 total; [class_746['PLAYER'/1, l='ClientLevel', x=3.50, y=-60.00, z=3.50]]
	Chunk stats: 961, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 111 game time, 6000 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:125)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Mixins in Stacktrace:
	net.minecraft.class_638:
		io.github.fabricators_of_create.porting_lib.client_events.mixin.client.ClientLevelMixin (porting_lib_client_events.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.ClientWorldMixin (fabric-lifecycle-events-v1.client.mixins.json)
		io.github.fabricators_of_create.porting_lib.entity.mixin.client.ClientLevelMixin (porting_lib_entity.mixins.json)
		dev.architectury.mixin.fabric.client.MixinClientLevel (architectury.mixins.json)
		io.github.fabricators_of_create.porting_lib.mixin.client.ClientLevelMixin (porting_lib_base.mixins.json)
		io.github.fabricators_of_create.porting_lib.transfer.mixin.client.ClientLevelMixin (porting_lib_transfer.mixins.json)
	net.minecraft.class_310:
		io.github.fabricators_of_create.porting_lib.mixin.client.MinecraftMixin (porting_lib_base.mixins.json)
		net.fabricmc.fabric.mixin.networking.client.accessor.MinecraftClientAccessor (fabric-networking-api-v1.client.mixins.json)
		io.github.fabricators_of_create.porting_lib.data.mixin.MinecraftMixin (porting_lib_data.mixins.json)
		io.github.fabricators_of_create.porting_lib.entity.mixin.client.MinecraftMixin (porting_lib_entity.mixins.json)
		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (fabric-events-interaction-v0.client.mixins.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (fabric-registry-sync-v0.client.mixins.json)
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.client.mixins.json)
		io.github.fabricators_of_create.porting_lib.common.mixin.client.accessor.MinecraftAccessor (porting_lib_common.mixins.json)
		io.github.fabricators_of_create.porting_lib.config.mixin.client.MinecraftMixin (porting_lib_config.mixins.json)
		dev.architectury.mixin.fabric.client.MixinMinecraft (architectury.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.client.mixins.json)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Mac OS X (aarch64) version 14.1
	Java Version: 21.0.1, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 2077227008 bytes (1980 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M2
	Identifier: Apple Inc. Family 0xda33d83d Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Avalanche + Blizzard
	Frequency (GHz): 3.50
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M2
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 18432.00
	Virtual memory used (MB): 11761.53
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 537.06
	JVM Flags: 2 total; -Xms4096m -Xmx4096m
	Fabric Mods: 
		architectury: Architectury 9.1.12
		fabric-api: Fabric API 0.90.7+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.2+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.6+d7b148e077
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.2+1bc31aeb77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.14.24
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.20.1
		mixintrace: MixinTrace 1.1.1+1.17
		not-that-cc: Crafty Crashes 1.0
		porting_lib: Porting Lib 2.1.1158+1.20-entity-refactor
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			mm: Manningham Mills 2.3
			porting_lib_accessors: Porting Lib Accessors 2.1.1158+1.20-entity-refactor
			porting_lib_asm: Porting Lib ASM 2.1.1158+1.20-entity-refactor
			porting_lib_attributes: Porting Lib Attributes 2.1.1158+1.20-entity-refactor
			porting_lib_base: Porting Lib Base 2.1.1158+1.20-entity-refactor
			porting_lib_brewing: Porting Lib Brewing 2.1.1158+1.20-entity-refactor
			porting_lib_chunk_loading: Porting Lib Chunk Loading 2.1.1158+1.20-entity-refactor
			porting_lib_client_events: Porting Lib Client Events 2.1.1158+1.20-entity-refactor
			porting_lib_common: Porting Lib Common 2.1.1158+1.20-entity-refactor
			porting_lib_config: Porting Lib Config 2.1.1158+1.20-entity-refactor
			porting_lib_core: Porting Lib Core 2.1.1158+1.20-entity-refactor
			porting_lib_data: Porting Lib Data 2.1.1158+1.20-entity-refactor
			porting_lib_entity: Porting Lib Entity 2.1.1158+1.20-entity-refactor
			porting_lib_extensions: Porting Lib Extensions 2.1.1158+1.20-entity-refactor
			porting_lib_fluids: Porting Lib Fluids 2.1.1158+1.20-entity-refactor
			porting_lib_gametest: Porting Lib GameTest 2.1.1158+1.20-entity-refactor
			porting_lib_items: Porting Lib Items 2.1.1158+1.20-entity-refactor
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1158+1.20-entity-refactor
			porting_lib_loot: Porting Lib Loot 2.1.1158+1.20-entity-refactor
			porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.1.1158+1.20-entity-refactor
			porting_lib_model_builders: Porting Lib Model Builders 2.1.1158+1.20-entity-refactor
			porting_lib_model_generators: Porting Lib Model Generators 2.1.1158+1.20-entity-refactor
			porting_lib_model_loader: Porting Lib Model Loader 2.1.1158+1.20-entity-refactor
			porting_lib_model_materials: Porting Lib Model Materials 2.1.1158+1.20-entity-refactor
			porting_lib_models: Porting Lib Models 2.1.1158+1.20-entity-refactor
			porting_lib_networking: Porting Lib Networking 2.1.1158+1.20-entity-refactor
			porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1158+1.20-entity-refactor
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 2.1.1158+1.20-entity-refactor
			porting_lib_registries: Porting Lib Registries 2.1.1158+1.20-entity-refactor
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.1.1158+1.20-entity-refactor
			porting_lib_transfer: Porting Lib Transfer 2.1.1158+1.20-entity-refactor
			porting_lib_utility: Porting Lib Utility 2.1.1158+1.20-entity-refactor
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		tamago: Tamago 2.1
			bytecode-junkie: Bytecode Junkie 0.3.3
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Apple M2 GL version 4.1 Metal - 88, Apple
	Window size: 1708x960
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	GPU Warnings: version: Metal
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	CPU: 8x Apple M2
	Server Running: true
	Player Count: 1 / 8; [class_3222['PLAYER'/1, l='ServerLevel[TEST]', x=3.50, y=-60.00, z=3.50]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
```
</details>

Versions:
- Minecraft `1.20.1`
- Fabric Loader `0.14.24`
- Fabric API `0.90.7+1.20.1`
- Architectury API `9.1.12` (Tamago's mixins fail to apply without it lol)
- Porting Lib `2.1.1158+1.20-entity-refactor`
- Tamago `2.1`

**Comment by AlphaMode** [comment]
oh no
